import { faEnvelope, faPhone, faMapMarkerAlt } from '@fortawesome/free-solid-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';

export const headerText = {
  name: 'Fabio Flores Manrique',
  profession: 'Full-Stack Web Developer'
};

export const contactItems = [
  {
    icon: faEnvelope,
    value: 'efabiofm@gmail.com'
  },
  {
    icon: faPhone,
    value: '(+506) 7015-4077'
  },
  {
    icon: faMapMarkerAlt,
    value: 'San José, Costa Rica'
  },
  {
    icon: faGithub,
    value: 'github.com/efabiofm'
  }
];

export const educationItems = [
  {
    from: 'Jan. 2014',
    to: 'To Date',
    institute: 'Cenfotec University, CR',
    degree: 'Bachelor\'s in Software Engineering'
  },
  {
    from: 'Jan. 2011',
    to: 'Dec. 2012',
    institute: 'National Technical University, CR',
    degree: 'Associate\'s in Electronics'
  }
];

export const languagesItems = [
  {
    language: 'English',
    level: 'C1 BELT Standard February 2019',
    percentage: 85
  },
  {
    language: 'Spanish',
    level: 'Native',
    percentage: 100
  }
];

export const summaryItems = [
  'Full-stack web developer with 4+ years of experience building web and hybrid applications for multiple business areas.',
  'Knowledge in functional programming, test-driven development, continuous delivery and agile methodologies.',
  'Critical thinking with self-motivation, adaptability, problem-solving and fast learning skills.'
];

export const experienceItems = [
  {
    from: 'Feb. 2019',
    to: 'To Date',
    company: 'Gorilla Logic LLC',
    position: 'Web Developer',
    description: [
      'Create custom JavaScript logic to add extra functionality to landing pages generated by the business in Unbounce which helps to manage A/B testing.',
      'Generate user-centered landing pages and interactive lead generation forms using React.',
      'Create reusable React components to speed up the nlanding pages delivery process.',
      'Create AWS lambda functions for landing pages to consume.'
    ]
  },
  {
    from: 'Sep. 2015',
    to: 'Feb. 2019',
    company: 'Ciris Informatic Solutions',
    position: 'Web Developer',
    description: [
      'Design and develop custom web apps using Angular, Vue.js, as well as hybrid apps using Ionic and NativeScript.',
      'Create REST APIs using Node.js and Express.js.',
      'Structure databases such as MongoDB and Firebase.',
      'Install and maintain Linux servers.',
      'Setup continuous integration and delivery pipelines.',
      'Research and implement new or alternative technologies.'
    ]
  },
  {
    from: 'Oct. 2014',
    to: 'Sep. 2015',
    company: 'Sykes Latin America',
    position: 'Customer Service Agent',
    description: 'Responsible for providing high quality and accurate resolutions to Intel’s internal customers in the United States by answering general inquiries via phone or email.'
  },
  {
    from: 'Jan. 2013',
    to: 'Apr. 2014',
    company: 'Ingram Micro CR',
    position: 'Electronic Technician',
    description: 'Responsible for repairing mobile devices from a wide range of well-known brands coming from T-Mobile in the United States, going from the troubleshooting process to circuit board components replacement.'
  }
];

export const skillsItems = [
  'JavaScript',
  'Java',
  'C++',
  '.NET',
  'Git',
  'React.js',
  'Vue.js',
  'Angular',
  'Node.js',
  'Ionic',
  'NativeScript',
  'HTML',
  'CSS/Sass',
  'AWS',
  'PWA',
  'Webpack',
  'MongoDB',
  'Firebase',
  'MySQL',
  'Jest',
  'JUnit',
  'Selenium',
  'CD/CI',
  'RESTful',
  'Scrum',
  'Linux'
];

export const referencesItems = [
  {
    name: 'Pablo Peraza Vargas',
    position: 'Developer',
    company: 'Gorilla Logic',
    phone: '(+506) 8710-6245',
    email: 'piousp@gmail.com'
  },
  {
    name: 'Melissa Odio Aguilar',
    position: 'Accountant',
    company: 'Citi Bank',
    phone: '(+506) 6023-4415',
    email: 'melissaodio@hotmail.com'
  }
];
